# See also: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '-'
    groups:
      aws-dependencies:
        patterns:
          - "@aws-sdk/*"
          - "@aws-lambda-powertools/*"
          - "@types/aws-lambda"
      test-dependencies:
        patterns:
          - "@types/jest"
          - "@typescript-eslint/*"
          - "ts-jest"
          - "jest"
          - "@cucumber/*"
      build-dependencies:
        patterns:
          - "@babel/*"
          - "@tsconfig/*"
          - "@types/node"
          - "esbuild"
          - "typescript"
          - "eslint*"
          - "@eslint/*"
          - "lint-staged"
          - "prettier"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: '-'
