version = 0.1

[default.deploy.parameters]
resolve_s3 = true
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "VpcStackName=\"vpc\" LogGroupRetentionInDays=\"30\""
image_repositories = []
