AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
Description: >
  ipv-identity-reuse-service

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  GovUKAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub experimentgovassets-${AWS::StackName}

  ExperimentApi:
    Type: AWS::Serverless::Api
    # Type: AWS::ApiGateway::RestApi
    Properties:
      StageName: v1
      AlwaysDeploy: true
    
  AssetsItem:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ExperimentApi
      ParentId: !GetAtt ExperimentApi.RootResourceId
      PathPart: "{item+}"

  AssetsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ExperimentApi
      ResourceId: !Ref AssetsItem
      HttpMethod: GET
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.item: true
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            'method.response.header.Timestamp': true
            'method.response.header.Content-Length': true
            'method.response.header.Content-Type': true
            'method.response.header.Cache-Control': true
      Integration:
        Type: AWS
        IntegrationHttpMethod: GET
        Credentials: !GetAtt AssetsResourceS3Role.Arn
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:s3:path/experimentgovassets-${AWS::StackName}/{item}
        PassthroughBehavior: WHEN_NO_MATCH
        RequestParameters:
          integration.request.path.item: method.request.path.item
        IntegrationResponses:
        - StatusCode: "200"
          ResponseParameters:
            'method.response.header.Timestamp': 'integration.response.header.Date'
            'method.response.header.Content-Length': 'integration.response.header.Content-Length'
            'method.response.header.Content-Type': 'integration.response.header.Content-Type'
            'method.response.header.Cache-Control': "'public, max-age=10'"

  AssetsResourceS3Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  ExperimentLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./node_modules
      CompatibleRuntimes:
        - nodejs22.x

  ExperimentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "."
      Handler: experiment.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref ExperimentApi
      Layers:
        - !Ref ExperimentLayer
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/handlers/experiment.ts
        Target: es2022
        Minify: true
        Sourcemap: true
        External:
          - govuk-frontend
