name: pact-tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  pact-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: npm
          registry-url: "https://npm.pkg.github.com/"
          scope: "@govuk-one-login"
          always-auth: true

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Pact Consumer tests
        run: npm run test:consumer

      - name: Run Pact Provider tests
        run: npm run test:provider
        env:
          PACT_TYPE: file
