name: pre-commit

on:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Pull repository
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Run pre-commit
        uses: govuk-one-login/github-actions/code-quality/run-pre-commit@5597473c825eb4db0c0f97529a419f0a09cd56f7
        with:
          all-files: true
          pull-repository: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-gitlint:
    if: ${{ !github.event.pull_request.draft }}
    name: Run Gitlint
    runs-on: ubuntu-latest
    steps:
      - name: Calculate fetch depth
        id: calculate-fetch-depth
        env:
          NUMBER_OF_PR_COMMITS: ${{ github.event.pull_request.commits }}
        run: |
          echo "Number of PR ${NUMBER_OF_PR_COMMITS}"
          echo "FETCH_DEPTH=$(($NUMBER_OF_PR_COMMITS + 1))" >> "${GITHUB_OUTPUT}"

      - name: Pull repository
        uses: actions/checkout@v7
        with:
          fetch-depth: ${{ steps.calculate-fetch-depth.outputs.FETCH_DEPTH }}

      - name: Install gitlint
        shell: bash
        run: |
          python -m pip install gitlint==0.19.1

      - name: Run gitlint
        shell: bash
        run: |
          gitlint --commits "${{ github.event.pull_request.base.sha }}..HEAD" --fail-without-commits --ignore-stdin
