name: Pre-merge checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: built-code
      aws-region: eu-west-2
    permissions:
      contents: read

  run-tests:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  pre-commit:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/pre-commit.yml
    permissions:
      contents: read
