name: pre-merge-checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: built-code
      aws-region: eu-west-2
    permissions:
      contents: read
      packages: read

  run-tests:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
      packages: read
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  run-pact-tests:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/pact-tests.yml
    permissions:
      contents: read
      packages: read

  pre-commit:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/pre-commit.yml
    permissions:
      contents: read
      packages: read

  preview:
    if: ${{ !github.event.pull_request.draft && contains( github.event.pull_request.labels.*.name, 'deploy')}}
    uses: ./.github/workflows/deploy-to-aws.yml
    needs:
      - build
    permissions:
      id-token: write
      contents: read
    with:
      stack-name: preview-pr-${{ github.event.pull_request.number }}
    secrets:
      aws-role-arn: ${{ secrets.GHA_AWS_ROLE_ARN }}
      aws-s3-bucket: ${{ secrets.GHA_SAM_DEPLOYMENT_BUCKET }}

  acceptance-test:
    if: ${{ !github.event.pull_request.draft && contains( github.event.pull_request.labels.*.name, 'deploy')}}
    uses: ./.github/workflows/acceptance-tests.yml
    needs:
      - preview
    permissions:
      id-token: write
      contents: read
    with:
      stack-name: ${{ needs.preview.outputs.stack-name }}
    secrets:
      aws-role-arn: ${{ secrets.GHA_AWS_ROLE_ARN }}
