name: test

on:
  workflow_call:
    secrets:
      sonar-token:
        required: true

permissions:
  contents: read
  packages: read

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Shallow clones disabled to improve performance

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: npm
          registry-url: "https://npm.pkg.github.com/"
          scope: "@govuk-one-login"
          always-auth: true

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit tests
        run: npm run test

      - name: Linting
        run: npm run lint

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        if: ${{ github.actor != 'dependabot[bot]' && env.ACT != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.sonar-token }}
